import { Inter, Libre_Baskerville } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import LanguageProvider from './components/LanguageContext';
import UserProvider from './components/UserContext';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const libre = Libre_Baskerville({
  variable: '--font-libre',
  subsets: ['latin'],
  weight: '400',
  style: ['italic', 'normal'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <UserProvider>
        <LanguageProvider>
          <body className={`${inter.variable} ${libre.variable}`}>
            <Header />
            {children}
          </body>
        </LanguageProvider>
      </UserProvider>
    </html>
  );
}
